### ISSUE TITLE
unable to run the game: ValueError: Source and destination surfaces need the same format.

### ISSUE THREAD

**Issue by rayenough** [deepmind/pysc2#11]
when i use python -m pysc2.bin.play --map Simple64 command, the error message of 
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ray_enough/.local/lib/python2.7/site-packages/pysc2/lib/renderer_human.py", line 878, in render_thread
    self.render_obs(obs)
  File "/home/ray_enough/.local/lib/python2.7/site-packages/pysc2/lib/renderer_human.py", line 56, in _with_lock
    return func(*args, **kwargs)
  File "/home/ray_enough/.local/lib/python2.7/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/home/ray_enough/.local/lib/python2.7/site-packages/pysc2/lib/renderer_human.py", line 894, in render_obs
    surf.draw(surf)
  File "/home/ray_enough/.local/lib/python2.7/site-packages/pysc2/lib/renderer_human.py", line 839, in draw_screen
    self.draw_base_map(surf)
  File "/home/ray_enough/.local/lib/python2.7/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/home/ray_enough/.local/lib/python2.7/site-packages/pysc2/lib/renderer_human.py", line 775, in draw_base_map
    surf.blit_np_array(out)
  File "/home/ray_enough/.local/lib/python2.7/site-packages/pysc2/lib/renderer_human.py", line 124, in blit_np_array
    pygame.transform.scale(raw_surface, self.surf.get_size(), self.surf)
ValueError: Source and destination surfaces need the same format.

**Comment by tewalds** [comment]
Which version of python, numpy and pygame are you using?

**Comment by rayenough** [comment]
I tried both 2.7 and 3.6, no luck. What's the requirements for package version?

**Comment by DengpanFu** [comment]
I had the same problems, and i use python2.7.12 with Anaconda4.2.0, pygame=1.9.3, numpy=1.13.0. Have you solved this problem?@rayenough, or any advice is appreciate@tewalds

**Comment by DengpanFu** [comment]
I have solved my problem, i traced this error and found that, raw_surface's third dimension is not the same as self.surf, in my case, raw_surface's shape is (84x84x16) while self.surf is (561x561x32), so when you try to use pygame.transform.scale(), it may cause an exception. 
The solution is, make the following modification: 
self._window = pygame.display.set_mode(window_size_px) to self._window = pygame.display.set_mode(window_size_px, 0, 32) in pysc2/lib/renderer_human.py at line 260.

**Comment by tewalds** [comment]
Thanks! I'll submit this fix when I'm back at the office, maybe over the weekend, but probably Monday. Out of curiosity, which OS is this on?

**Comment by rayenough** [comment]
I use it on ubuntu.

**Comment by tewalds** [comment]
This should be fixed in 2bf26d7
