### ISSUE TITLE
WebSocketTimeoutException (Bash on Windows)

### ISSUE THREAD

**Issue by neighthan** [deepmind/pysc2#15]
I'm running Ubuntu 16.04 on Windows 10, Python 3.6.1 (Anaconda distribution). Everything seems to have installed fine (`pysc2`, maps), but when I run `pysc2_agent --map Simple64` I get the following output and error. Do I need to have an X server or something set up for this to work? I assumed, even if no graphical output was on my screen, that it would be able to run a bot and save a reply of the match.

```
pysc2_agent --map Simple64
Version: B55958 (SC2.3.16)
Build: Jul 31 2017 13:19:41
Command Line: '"/home/neighthan/StarCraftII/Versions/Base55958/SC2_x64" -listen 127.0.0.1 -port 20058 -dataDir /home/neighthan/Star
CraftII/ -tempDir /tmp/sc-6h55h2cr/ -displayMode 0'
Starting up...
Startup Phase 1 complete
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:20058 (20058)
Startup Phase 3 complete. Ready for commands.
Requesting to join a single player game
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface enabled
Configure: score interface enabled
Configure: render interface disabled
Entering load game phase.
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_socket.py", line 80, in recv
    bytes_ = sock.recv(bufsize)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neighthan/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/neighthan/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/bin/agent.py", line 74, in run_thread
    visualize=visualize) as env:
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/env/sc2_env.py", line 178, in __init__
    self._controller.join_game(join)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 80, in _valid_status
    return func(self, *args, **kwargs)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 55, in _check_error
    return check_error(func(*args, **kwargs), error_enum)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 120, in join_game
    return self._client.send(join_game=req_join_game)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/protocol.py", line 127, in send
    res = self.send_req(sc_pb.Request(**kwargs))
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/protocol.py", line 113, in send_req
    return self.read()
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/protocol.py", line 86, in read
    response = self._read()
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/protocol.py", line 152, in _read
    response_str = self._sock.recv()
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_abnf.py", line 340, in recv_frame
    self.recv_header()
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_abnf.py", line 288, in recv_header
    header = self.recv_strict(2)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_abnf.py", line 375, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_socket.py", line 83, in recv
    raise WebSocketTimeoutException(message)
websocket._exceptions.WebSocketTimeoutException: timed out

WARNING:root:Terminating attempt 0...
WARNING:root:Terminated.
```

I also installed pysc2 and SC2 on Windows, and there things run fine (I do, of course, have the Linux SC2 installed as well). Ubuntu on Windows is probably a niche market, so if it's not entirely supported, I'll understand.

I wasn't sure where to ask this, especially as the project is so new, but if there's a Google group or such that would be better (as this is probably not an *issue* in `pysc2` so much as a problem with my setup), please let me know.

**Comment by JustinMBrown** [comment]
I was having a socket issue as well, and I fixed it by updating SC2. They released the required version 4 days ago. It wasn't the exact same error, so updating may or may not help, but it's worth double checking.

**Comment by tewalds** [comment]
That is the correct version (55958), so I'm not sure what's wrong.

Maybe modify lib/sc_process.py around line 70 with the extra arg "-verbose" to see if SC2 gives a better error message.

**Comment by neighthan** [comment]
Okay, I made the following edit (only the '-verbose' part was added; the rest is for context):

```
args = [
        run_config.exec_path,
        "-listen", "127.0.0.1",
        "-port", str(self._port),
        "-dataDir", os.path.join(run_config.data_dir, ""),
        "-tempDir", os.path.join(self._tmp_dir, ""),
        "-displayMode", "1" if full_screen else "0",
        '-verbose',
    ]
```

And then the error message that I get is:

```
pysc2_agent --map Simple64
Version: B55958 (SC2.3.16)
Build: Jul 31 2017 13:19:41
Command Line: '"/home/neighthan/StarCraftII/Versions/Base55958/SC2_x64" -listen 127.0.0.1 -port 23630 -dataDir /home/neighthan/StarCraftI
I/ -tempDir /tmp/sc-7_iz5kkk/ -displayMode 0 -verbose'
Starting up...
Startup Phase 1 complete
Startup Phase 2 complete
Creating stub renderer...
Request menus.
Startup Input.
Startup Resource manager.
Startup Gfx.
Startup BattleNet.
Startup GameUI.
Startup Galaxy.
Startup UI.
Startup Local.
Startup Game.
Startup ResourceCache.
Startup CGlueUI.
Startup BattleUI.
InitializingAppGameStateLogging
ResponseThread: Waiting for response to send...
Listening on: 127.0.0.1:23630 (23630)
Begin initial poll
Initial Poll 1
Initial Poll 2
Initial Poll 3
Initial Poll 4
Initial Poll 5
Initial Poll 6
Initial Poll 7
Initial Poll 8
Initial Poll 9
Initial Poll 10
End initial poll
Startup Phase 3 complete. Ready for commands.
RequestThread: Received a request.
CSocketBuffer: Queueing request...
CSocketBuffer: Request queued!
MainThread: Processing request type 19
MainThread: Sending response type 19
CSocketBuffer: Queueing response...
CSocketBuffer: Response queued!
MainThread: Response Sent.
ResponseThread: Response found!
ResponseThread: Response sent!
ResponseThread: Waiting for response to send...
RequestThread: Received a request.
CSocketBuffer: Queueing request...
CSocketBuffer: Request queued!
MainThread: Processing request type 1
MainThread: Sending response type 1
CSocketBuffer: Queueing response...
CSocketBuffer: Response queued!
MainThread: Response Sent.
ResponseThread: Response found!
ResponseThread: Response sent!
ResponseThread: Waiting for response to send...
RequestThread: Received a request.
CSocketBuffer: Queueing request...
CSocketBuffer: Request queued!
MainThread: Processing request type 2
Requesting to join a single player game
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface enabled
Configure: score interface enabled
Configure: render interface disabled
Entering load game phase.
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
ResponseThread: Waiting for response to send...
[The above line is repeated many times; omitted for brevity]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_socket.py", line 80, in recv
    bytes_ = sock.recv(bufsize)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neighthan/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/neighthan/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/bin/agent.py", line 74, in run_thread
    visualize=visualize) as env:
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/env/sc2_env.py", line 178, in __init__
    self._controller.join_game(join)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 80, in _valid_status
    return func(self, *args, **kwargs)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 55, in _check_error
    return check_error(func(*args, **kwargs), error_enum)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 120, in join_game
    return self._client.send(join_game=req_join_game)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/protocol.py", line 127, in send
    res = self.send_req(sc_pb.Request(**kwargs))
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/protocol.py", line 113, in send_req
    return self.read()
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/protocol.py", line 86, in read
    response = self._read()
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/pysc2/lib/protocol.py", line 152, in _read
    response_str = self._sock.recv()
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_abnf.py", line 340, in recv_frame
    self.recv_header()
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_abnf.py", line 288, in recv_header
    header = self.recv_strict(2)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_abnf.py", line 375, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/home/neighthan/anaconda3/lib/python3.6/site-packages/websocket/_socket.py", line 83, in recv
    raise WebSocketTimeoutException(message)
websocket._exceptions.WebSocketTimeoutException: timed out

ResponseThread: Waiting for response to send...
[the above repeats a few times]
WARNING:root:Terminating attempt 0...
WARNING:root:Terminated.
```

**Comment by tewalds** [comment]
Try increasing the timeout: https://github.com/deepmind/pysc2/blob/master/pysc2/lib/sc_process.py#L139 . You could also run pysc2 with "--sc2_verbose 20" (or some larger number if you want to see more of what pysc2 is sending to SC2). 

@KevinCalderone Any idea why JoinGame times out (2 minutes) on Ubuntu on Windows for Simple64?

**Comment by KevinCalderone** [comment]
We have not tested the Ubuntu windows subsystem. Probably not that high on our list of priorities at the moment.
