### ISSUE TITLE
PYCS2 agent on linux server - /pysc2/run_configs/platforms.py ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by slimak2** [deepmind/pysc2#152]
Hello, i am trying to run simple PYCS2 agent on linux server, and it throws me this error.
could someone tell me what it means and what can i do to fix it?

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xkraji11/.local/lib/python3.5/site-packages/pysc2/bin/agent.py", line 112, in <module>
    app.run(main)
  File "/home/xkraji11/.local/lib/python3.5/site-packages/absl/app.py", line 274, in run
    _run_main(main, argv)
  File "/home/xkraji11/.local/lib/python3.5/site-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "/home/xkraji11/.local/lib/python3.5/site-packages/pysc2/bin/agent.py", line 98, in main
    run_thread(agent_cls, FLAGS.map, FLAGS.render)
  File "/home/xkraji11/.local/lib/python3.5/site-packages/pysc2/bin/agent.py", line 74, in run_thread
    visualize=visualize) as env:
  File "/home/xkraji11/.local/lib/python3.5/site-packages/pysc2/env/sc2_env.py", line 132, in __init__
    self._setup((agent_race, bot_race, difficulty), **kwargs)
  File "/home/xkraji11/.local/lib/python3.5/site-packages/pysc2/env/sc2_env.py", line 185, in _setup
    self._launch(interface, player_setup)
  File "/home/xkraji11/.local/lib/python3.5/site-packages/pysc2/env/sc2_env.py", line 205, in _launch
    self._sc2_procs = [self._run_config.start()]
  File "/home/xkraji11/.local/lib/python3.5/site-packages/pysc2/run_configs/platforms.py", line 87, in start
    data_version=data_version, **kwargs)
  File "/home/xkraji11/.local/lib/python3.5/site-packages/pysc2/run_configs/lib.py", line 104, in start
    return sc_process.StarcraftProcess(self, **kwargs)
  File "/home/xkraji11/.local/lib/python3.5/site-packages/pysc2/lib/sc_process.py", line 67, in __init__
    exec_path = run_config.exec_path(game_version)
  File "/home/xkraji11/.local/lib/python3.5/site-packages/pysc2/run_configs/platforms.py", line 73, in exec_path
    build_version = max(int(v[4:]) for v in os.listdir(versions_dir)
ValueError: max() arg is an empty sequence

**Comment by tewalds** [comment]
It looks like it isn't finding any versions of SC2 where you're pointing it at. Did you install the game correctly? Admittedly it could use a better error message.

**Comment by tewalds** [comment]
Better error message in 5339c11 .
