### ISSUE TITLE
Replay can't play game version

### ISSUE THREAD

**Issue by RohanArepally** [deepmind/pysc2#157]
Hi I'm running `python -m pysc2.bin.play --replay` just like in the README.md

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/Rohan/code/sc2/pysc2/pysc2/bin/play.py", line 199, in <module>
    app.run(main)
  File "/Users/Rohan/code/sc2/env/lib/python2.7/site-packages/absl/app.py", line 274, in run
    _run_main(main, argv)
  File "/Users/Rohan/code/sc2/env/lib/python2.7/site-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "/Users/Rohan/code/sc2/pysc2/pysc2/bin/play.py", line 135, in main
    full_screen=FLAGS.full_screen) as controller:
  File "pysc2/run_configs/platforms.py", line 85, in start
    data_version = get_version(game_version)[1]
  File "pysc2/run_configs/platforms.py", line 48, in get_version
    game_version, sorted(VERSIONS.keys())))
ValueError: Unknown game version: 4.2.1. Known versions: ['3.16.1', '3.17.0', '3.17.1', '3.17.2', '3.18.0', '3.19.0']
```

Running on macOS High Sierra 10.13.3 in virtualenv
What is the fix for this?

**Comment by MLaurenceFournier** [comment]
We had the same problem in the student team I'm working in. Basically, pysc2 (play --replay) don't support recent versions of Starcraft. For that you would have to add hashes from https://github.com/Blizzard/s2client-proto/blob/master/buildinfo/versions.json to pysc2/run_configs/platforms.py just as this commit does: https://github.com/deepmind/pysc2/commit/c8ad5e8fdc0fff5549c575abea9acbf11d903fe0 .

I'm not sure it would be enough though. Anyways, as you can see, Blizzard as not yet released a hash for version 4.2.1. You could either use a older version Starcraft or try to skip the check.

If you are looking for a simple way to parse replays in the context of pysc2 I suggest looking into https://github.com/narhen/pysc2-replay and its forks who seems to simply skip the check.
