### ISSUE TITLE
New Map Causes Renderer To Crash

### ISSUE THREAD

**Issue by lfricken** [deepmind/pysc2#158]
I created a new 128x128 map using LOTV data, but it crashes the Renderer. Based on this information, I'm thinking there is something on the map that it doesn't know how to render to one of the feature screens? But I only added things that were on the DefeatRoaches.SC2Map. I inspected the Map Info tab and all subtabs. I can't find a single difference other than the texture tab, which surely doesn't matter (right?).

```
Exception in thread Renderer:
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\lib\renderer_human.py", line 889, in render_thread
    self.render_obs(obs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\lib\renderer_human.py", line 56, in _with_lock
    return func(*args, **kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\lib\stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\lib\renderer_human.py", line 905, in render_obs
    surf.draw(surf)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\lib\renderer_human.py", line 846, in draw_screen
    self.draw_base_map(surf)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\lib\stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\lib\renderer_human.py", line 775, in draw_base_map
    out *= visibility_fade[visibility]
IndexError: index 3 is out of bounds for axis 0 with size 3
```

**I tried printing out those variables to see what the difference was:**

DefeatRoaches.SC2Map (works):
```
visibility_fade =
[[0.5  0.5  0.5 ]
 [0.75 0.75 0.75]
 [1.   1.   1.  ]]

visibility =
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
len(visibility) = 84
```

NewMap.SC2Map (crashes renderer):
```
visibility_fade =
[[0.5  0.5  0.5 ]
 [0.75 0.75 0.75]
 [1.   1.   1.  ]]

visibility =
[[0 0 0 ... 2 2 2]
 [0 0 0 ... 2 2 2]
 [0 0 0 ... 2 2 2]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
len(visibility) = 84
```

**I actually don't understand how the visibility array is indexing the visibility_fade array at all.**

**Comment by tewalds** [comment]
I'm not sure what visibility=3 means... Can you attach the map file?

**Comment by alexzhang13** [comment]
Are you using a black mask? I had the same issue because I wanted to limit the visibility of my own unit. I believe visibility=3 refers to a black mask being applied on the map. I tried removing the black mask from my own map and the renderer no longer crashed.

**Comment by tewalds** [comment]
Ah, yeah, we don't support a black mask.
