### ISSUE TITLE
Getting random 'out of range for 2/select_point'

### ISSUE THREAD

**Issue by JevMar** [deepmind/pysc2#199]
Hey, I am seem to be having an issue with selecting Terran Barracks unit, while getting unit coordinates from feature_units. This happens rarely, however, results in a crash. 

While trying to figure out what the issue is, figured I'll keep track of what coordinates I get during training. Most of the time I get results like [1, 26], [1, 29], [5, 26] or [5, 29] for x and y, even though Barracks are spawned in exact same location each time. The crash happens when I get [-2, 29] with "Argument is out of range for 2/select_point". Seems to be happening randomly, once occurred after training for 150+ episodes, then once after 400+, then after 8, etc.

Some code below.
This is how I get barracks unit info:
   ```
     barracks_list = self.get_units_by_type(obs, units.Terran.Barracks)

        if len(barracks_list) > 0:
            barracks = barracks_list[0]
```

**def** get_units_by_type ([Source](https://github.com/skjb/pysc2-tutorial/blob/master/Build%20a%20Zerg%20Bot/zerg_agent_step7.py))
```
    def get_units_by_type(self, obs, unit_type):
        return [unit for unit in obs.observation.feature_units
                if unit.unit_type == unit_type]
```

How I select the barracks:
`return actions.FUNCTIONS.select_point("select", (barracks.x, barracks.y))`

Output just before error:
```
Game has started.
I0619 20:25:50.108715 139850130720576 sc2_env.py:433] Starting episode: 176
Barracks coord.:  1  &  26
I0619 20:25:58.141600 139850130720576 sc2_env.py:510] Episode 176 finished after 9600 game steps. Outcome: [1], reward: [0], score: [0]
episode: 176   reward: -299
..........................................................................
Game has started.
I0619 20:25:58.680646 139850130720576 sc2_env.py:433] Starting episode: 177
Barracks coord.:  5  &  26
I0619 20:26:01.617632 139850130720576 sc2_env.py:510] Episode 177 finished after 3408 game steps. Outcome: [1], reward: [1], score: [1]
episode: 177   reward: 196
..........................................................................
Game has started.
I0619 20:26:02.163400 139850130720576 sc2_env.py:433] Starting episode: 178
Barracks coord.:  1  &  29
I0619 20:26:10.197444 139850130720576 sc2_env.py:510] Episode 178 finished after 9600 game steps. Outcome: [1], reward: [0], score: [0]
episode: 178   reward: -299
..........................................................................
Game has started.
I0619 20:26:10.745496 139850130720576 sc2_env.py:433] Starting episode: 179
Barracks coord.:  -2  &  29
I0619 20:26:10.764039 139850130720576 sc2_env.py:531] Environment Close
RequestQuit command received.
unable to parse websocket frame.
Closing Application...
Terminate action already called.
Entering core terminate.
Core shutdown finished.
I0619 20:26:12.267772 139850130720576 sc_process.py:197] Shutdown gracefully.
I0619 20:26:12.268002 139850130720576 sc_process.py:182] Shutdown with return code: 0
Traceback (most recent call last):
  File "Agent.py", line 320, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 274, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "Agent.py", line 313, in main
    timesteps = env.step(step_actions)
  File "/usr/local/lib/python3.6/dist-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pysc2/env/sc2_env.py", line 449, in step
    self._controllers, self._features, self._obs, actions))
  File "/usr/local/lib/python3.6/dist-packages/pysc2/lib/run_parallel.py", line 54, in run
    funcs = [f if callable(f) else functools.partial(*f) for f in funcs]
  File "/usr/local/lib/python3.6/dist-packages/pysc2/lib/run_parallel.py", line 54, in <listcomp>
    funcs = [f if callable(f) else functools.partial(*f) for f in funcs]
  File "/usr/local/lib/python3.6/dist-packages/pysc2/env/sc2_env.py", line 448, in <genexpr>
    for c, f, o, a in zip(
  File "/usr/local/lib/python3.6/dist-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pysc2/lib/features.py", line 969, in transform_action
    func, func_call.arguments))
ValueError: Argument is out of range for 2/select_point (6/select_point_act [4]; 0/screen [0, 0]), got: [[<SelectPointAct.select: 0>], [-2, 29]]
I0619 20:26:12.357553 139850130720576 sc2_env.py:531] Environment Close
```

**Comment by ai2010** [comment]
I have the same problem too.
