### ISSUE TITLE
ValueError: Unknown ability_id: 3674, type: cmd_quick. Likely a bug.

### ISSUE THREAD

**Issue by matthewgan** [deepmind/pysc2#214]
"/pysc2/lib/features.py", line 1020, in func_call_ability
    ability_id, cmd_type.__name__))
ValueError: Unknown ability_id: 3674, type: cmd_quick. Likely a bug.

Keep getting this error printed out on the screen, but not regularly, can happend anywhere during the step function of my agent.

**Comment by matthewgan** [comment]
More log:

Took 2.936 seconds for 155 steps: 52.786 fps
I0725 11:01:55.927479 139631057532672 sc2_env.py:531] Environment Close
RequestQuit command received.
Closing Application...
unable to parse websocket frame.
User leave event received.
Terminate action already called.
Entering core terminate.
Core shutdown finished.
I0725 11:01:56.930166 139631057532672 sc_process.py:197] Shutdown gracefully.
I0725 11:01:56.930352 139631057532672 sc_process.py:182] Shutdown with return code: 0
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/bin/agent.py", line 148, in <module>
    app.run(main)
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/absl/app.py", line 274, in run
    _run_main(main, args)
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/bin/agent.py", line 134, in main
    run_thread(agent_classes, players, FLAGS.map, FLAGS.render)
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/bin/agent.py", line 97, in run_thread
    run_loop.run_loop(agents, env, FLAGS.max_agent_steps, FLAGS.max_episodes)
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/env/run_loop.py", line 48, in run_loop
    timesteps = env.step(actions)
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/env/available_actions_printer.py", line 32, in step
    all_obs = super(AvailableActionsPrinter, self).step(*args, **kwargs)
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/env/base_env_wrapper.py", line 42, in step
    return self._env.step(*args, **kwargs)
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/env/sc2_env.py", line 452, in step
    return self._step()
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/env/sc2_env.py", line 461, in _step
    self._features, self._obs)]
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/env/sc2_env.py", line 460, in <listcomp>
    agent_obs = [f.transform_obs(o) for f, o in zip(
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/lib/features.py", line 752, in transform_obs
    [self.reverse_action(a).function for a in obs.actions],
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/lib/features.py", line 752, in <listcomp>
    [self.reverse_action(a).function for a in obs.actions],
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/lib/features.py", line 1078, in reverse_action
    return func_call_ability(cmd.ability_id, actions.cmd_quick, queue)
  File "/home/matthew/pyscenv/lib/python3.5/site-packages/pysc2/lib/features.py", line 1020, in func_call_ability
    ability_id, cmd_type.__name__))
ValueError: Unknown ability_id: 3674, type: cmd_quick. Likely a bug.
I0725 11:01:56.974716 139631057532672 sc2_env.py:531] Environment Close
I0725 11:01:56.974978 139631057532672 sc2_env.py:531] Environment Close

**Comment by janbolle** [comment]
same problem here.
### Solution
Use StarcraftII Version 4.1.2,
there also will be a failure in the first run, but the game won't crash.

**Comment by lusensama** [comment]
@inoryy Tried reinstalling pysc2 from source, still no luck!

**Comment by TianChenone** [comment]
hi, have you solved the problem?

**Comment by TianChenone** [comment]
> Same problem here.
> 
> I am using windows. How can I change the original official SC2 version to 4.1.2? Also, I need to access replays of older versions, can you still access the replay after its version being changed?

Hi, I change the version of SC2, too. I wonder have you found the replay of version 4.1.2？ Thank you.

**Comment by TianChenone** [comment]
@lusensama Hi, I change the version of SC2, too. I wonder have you found the replay of version 4.1.2？ Thank you.

**Comment by HumphB** [comment]
The command and command type combinations are probably just missing from actions._FUNCTIONS.

I noticed the issue with tactical jump being used on the minimap, it's a valid action but is missing.
As a work around you can add the missing items to the list yourself.

**Comment by lusensama** [comment]
> @lusensama Hi, I change the version of SC2, too. I wonder have you found the replay of version 4.1.2？ Thank you.

I just cleaned up my replays to a single version and skipped all replays with this error.
