### ISSUE TITLE
Problem occured when try to rest the env

### ISSUE THREAD

**Issue by chauvinfish** [deepmind/pysc2#215]
Traceback (most recent call last):
  File "C:\Users\yanshengyang\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\yanshengyang\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\yanshengyang\Desktop\4rChon\2018.3.12\agents\a3c\agent.py", line 106, in <lambda>
    worker_fn = lambda worker=worker: worker.run(coord, FLAGS.max_t)
  File "C:\Users\yanshengyang\Desktop\4rChon\2018.3.12\agents\a3c\worker.py", line 266, in run
    for recorder, is_done in runner.run_n_steps():
  File "C:\Users\yanshengyang\Desktop\4rChon\2018.3.12\runner.py", line 35, in run_n_steps
    timesteps = self.env.reset()
  File "C:\Users\yanshengyang\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\env\base_env_wrapper.py", line 39, in reset
    return self._env.reset(*args, **kwargs)
  File "C:\Users\yanshengyang\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\lib\stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "C:\Users\yanshengyang\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\env\sc2_env.py", line 434, in reset
    self._metrics.increment_episode()
AttributeError: 'NoneType' object has no attribute 'increment_episode'

related codes in sc2_env.py
`  def reset(self):
    """Start a new episode."""
    self._episode_steps = 0
    if self._episode_count:
      # No need to restart for the first episode.
      self._restart()

    self._episode_count += 1
    logging.info("Starting episode: %s", self._episode_count)
    self._metrics.increment_episode()

    self._last_score = [0] * self._num_agents
    self._state = environment.StepType.FIRST
    return self._step()`

in runner.py
`    def run_n_steps(self):
        """A run loop to have agents and an environment interact."""
        if self.is_first_step:
            self.start_time = time.time()

        steps = 0
        replay_buffer = []

        try:
            # If starting new episode, reset agent and environment
            if self.is_first_step:
                timesteps = self.env.reset()
                self.timestep = timesteps[0]
                self.agent.reset()

            while True:
                assert(self.timestep is not None)

                action = self.agent.step(self.timestep)

                steps += 1

                # Yield current buffer if update_period is reached or episode finished
                is_update_ready = steps % self.update_period == 0
                is_done = self.timestep.last()

                replay_buffer.append([action, self.timestep])
                if is_update_ready or is_done:
                    print("Updating at {} - {}".format(steps, self.update_period))
                    yield replay_buffer, is_done
                if is_done:
                    self._reset()
                    break

                timesteps = self.env.step([action])
                self.timestep = timesteps[0]

        except KeyboardInterrupt:
            pass
        finally:
            elapsed_time = time.time() - self.start_time`

**Comment by tewalds** [comment]
It seems you're in a state where `reset` is called before the constructor finishes, since `self._metrics` is defined in `_finalize` which gets called from the constructor. I'm not sure how you got there...
