### ISSUE TITLE
version `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by hasdavid** [deepmind/pysc2#239]
Hello,

I tried running the agent on the university server, which uses CentOS 7.5, and this error showed up:

$ python3 -m pysc2.bin.agent --map Simple64
```
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
I1026 10:38:51.440092 140051309365056 sc_process.py:110] Launching SC2: /homes/eva/xh/xhasda00/StarCraftII/Versions/Base60321/SC2_x64 -listen 127.0.0.1 -port 23487 -dataDir /homes/eva/xh/xhasda00/StarCraftII/ -tempDir /tmp/sc-q9zq1pne/ -displayMode 0 -windowwidth 640 -windowheight 480 -windowx 50 -windowy 50 -eglpath libEGL.so
I1026 10:38:51.444874 140051309365056 remote_controller.py:127] Connecting to: ws://127.0.0.1:23487/sc2api, attempt: 0, running: True
/homes/eva/xh/xhasda00/StarCraftII/Versions/Base60321/SC2_x64: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /homes/eva/xh/xhasda00/StarCraftII/Libs/libstdc++.so.6)
I1026 10:38:51.453467 140051309365056 sc_process.py:197] Shutdown gracefully.
I1026 10:38:51.453639 140051309365056 sc_process.py:182] Shutdown with return code: 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/homes/eva/xh/xhasda00/.local/lib/python3.6/site-packages/pysc2/bin/agent.py", line 148, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/site-packages/absl/app.py", line 274, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/site-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "/homes/eva/xh/xhasda00/.local/lib/python3.6/site-packages/pysc2/bin/agent.py", line 134, in main
    run_thread(agent_classes, players, FLAGS.map, FLAGS.render)
  File "/homes/eva/xh/xhasda00/.local/lib/python3.6/site-packages/pysc2/bin/agent.py", line 94, in run_thread
    visualize=visualize) as env:
  File "/homes/eva/xh/xhasda00/.local/lib/python3.6/site-packages/pysc2/env/sc2_env.py", line 264, in __init__
    self._launch_sp(map_inst, interfaces[0])
  File "/homes/eva/xh/xhasda00/.local/lib/python3.6/site-packages/pysc2/env/sc2_env.py", line 331, in _launch_sp
    self._sc2_procs = [self._run_config.start()]
  File "/homes/eva/xh/xhasda00/.local/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 221, in start
    return super(Linux, self).start(extra_args=extra_args, **kwargs)
  File "/homes/eva/xh/xhasda00/.local/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 131, in start
    self, exec_path=exec_path, version=version, **kwargs)
  File "/homes/eva/xh/xhasda00/.local/lib/python3.6/site-packages/pysc2/lib/sc_process.py", line 116, in __init__
    self._host, self._port, self, timeout_seconds=timeout_seconds)
  File "/homes/eva/xh/xhasda00/.local/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 107, in __init__
    sock = self._connect(host, port, proc, timeout_seconds)
  File "/homes/eva/xh/xhasda00/.local/lib/python3.6/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/homes/eva/xh/xhasda00/.local/lib/python3.6/site-packages/pysc2/lib/remote_controller.py", line 129, in _connect
    return websocket.create_connection(url, timeout=timeout_seconds)
  File "/homes/eva/xh/xhasda00/.local/lib/python3.6/site-packages/websocket/_core.py", line 502, in create_connection
    websock.connect(url, **options)
  File "/homes/eva/xh/xhasda00/.local/lib/python3.6/site-packages/websocket/_core.py", line 219, in connect
    options.pop('socket', None))
  File "/homes/eva/xh/xhasda00/.local/lib/python3.6/site-packages/websocket/_http.py", line 122, in connect
    sock = _tunnel(sock, hostname, port, auth)
  File "/homes/eva/xh/xhasda00/.local/lib/python3.6/site-packages/websocket/_http.py", line 286, in _tunnel
    "failed CONNECT via proxy status: %r" % status)
websocket._exceptions.WebSocketProxyException: failed CONNECT via proxy status: 403
I1026 10:38:51.485915 140051309365056 sc2_env.py:531] Environment Close
```

The problem apparently resides in glibc 2.18 not being installed (glibc 2.17 is present in the system at the moment).
Does anyone have any idea how to correct or bypass this issue?
Note that I do not own admin rights on the server and contacting the administrator with a request to install a new version globally probably won't succeed.
Would it be possible to install glibc 2.18 in my home directory and change the game settings to use that library instead?
Or use an older version of the program which maybe doesn't need the glibc 2.18 library?
Or use some sort of virtual environment?
Or does the problem reside in something completely different?

I'm aiming to build my bachelor thesis in reinforcement learning on this environment and use the server's computational power to train the agent.

Thank you for any suggestions.

**Comment by hasdavid** [comment]
Ok, I now see that this is more of the SC2 Linux Package issue rather than of the environment itself. Found an opened issue here:
https://github.com/Blizzard/s2client-proto/issues/84
Still a shame, though.
