### ISSUE TITLE
pysc2.bin.play dosen't work

### ISSUE THREAD

**Issue by Rishav1** [deepmind/pysc2#254]
When I run the command `python -m pysc2.bin.play --map Simple64`, I receive the following stack-trace.
```
Traceback (most recent call last):
  File "/home/rishav/anaconda3/envs/osrl/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rishav/anaconda3/envs/osrl/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rishav/Desktop/repo/pysc2/pysc2/bin/play.py", line 218, in <module>
    app.run(main)
  File "/home/rishav/anaconda3/envs/osrl/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/rishav/anaconda3/envs/osrl/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/rishav/Desktop/repo/pysc2/pysc2/bin/play.py", line 154, in main
    controller.join_game(join)
  File "/home/rishav/Desktop/repo/pysc2/pysc2/lib/remote_controller.py", line 96, in _valid_status
    return func(self, *args, **kwargs)
  File "/home/rishav/Desktop/repo/pysc2/pysc2/lib/remote_controller.py", line 71, in _check_error
    return check_error(func(*args, **kwargs), error_enum)
  File "/home/rishav/Desktop/repo/pysc2/pysc2/lib/remote_controller.py", line 62, in check_error
    raise RequestError("%s.%s: '%s'" % (enum_name, error_name, details), res)
pysc2.lib.remote_controller.RequestError: SC2APIProtocol.ResponseJoinGame.Error.MissingOptions: 'Render interface not implemented.'
```

It seems as though the sc2client-proto dosen't implement render interface as I found it in one of the [comments](https://github.com/Blizzard/s2client-proto/blob/master/s2clientprotocol/sc2api.proto#L543). If the blizzard API doesn't support it, I am wondering how to get real game output through pysc2.

**Comment by Rishav1** [comment]
When I comment out the [following lines](https://github.com/deepmind/pysc2/blob/master/pysc2/bin/play.py#L118-L120), I seem to get it to work, but with feature_layer render only.

**Comment by keskival** [comment]
Workaround: Pass the flag `--rgb_screen_size 0` to `pysc2.bin.play`.

For example:
`python -m pysc2.bin.play --map Simple64 --rgb_screen_size 0`

**Comment by Rishav1** [comment]
Yeah but the real game interface stream is being bypassed by that. Dosen't solve the issue if you want to access the rgb rendering.

**Comment by tewalds** [comment]
The game does support it, at least new versions. You may need to install libmesa.
