### ISSUE TITLE
use_raw_units=True throws OverflowError

### ISSUE THREAD

**Issue by BurningSpy** [deepmind/pysc2#262]
When I set the use_raw_units flag on True in my agent it throws an OverflowError:
```
Traceback (most recent call last):
  File "qlearnsc2bot.py", line 670, in <module>
    app.run(main)
  File "C:\Users\Me\Anaconda3\envs\starcraft\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\Me\Anaconda3\envs\starcraft\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "qlearnsc2bot.py", line 658, in main
    timesteps = env.reset()
  File "C:\Users\Me\Anaconda3\envs\starcraft\lib\site-packages\pysc2\lib\stopwatch.py", line 201, in _stopwatch
    return func(*args, **kwargs)
  File "C:\Users\Me\Anaconda3\envs\starcraft\lib\site-packages\pysc2\env\sc2_env.py", line 471, in reset
    return self._observe()
  File "C:\Users\Me\Anaconda3\envs\starcraft\lib\site-packages\pysc2\env\sc2_env.py", line 530, in _observe
    self._get_observations()
  File "C:\Users\Me\Anaconda3\envs\starcraft\lib\site-packages\pysc2\env\sc2_env.py", line 526, in _get_observations
    for f, o in zip(self._features, self._obs)]
  File "C:\Users\Me\Anaconda3\envs\starcraft\lib\site-packages\pysc2\env\sc2_env.py", line 526, in <listcomp>
    for f, o in zip(self._features, self._obs)]
  File "C:\Users\Me\Anaconda3\envs\starcraft\lib\site-packages\pysc2\lib\stopwatch.py", line 201, in _stopwatch
    return func(*args, **kwargs)
  File "C:\Users\Me\Anaconda3\envs\starcraft\lib\site-packages\pysc2\lib\features.py", line 1032, in transform_obs
    for u in raw.units]
  File "C:\Users\Me\Anaconda3\envs\starcraft\lib\site-packages\pysc2\lib\features.py", line 1032, in <listcomp>
    for u in raw.units]
  File "C:\Users\Me\Anaconda3\envs\starcraft\lib\site-packages\pysc2\lib\features.py", line 1013, in full_unit_vec
    ), dtype=np.int32)
OverflowError: Python int too large to convert to C long
```

**Comment by tewalds** [comment]
This should be fixed now.
