### ISSUE TITLE
Failed to find .build.info file at path: /home/x/StarCraftII/.build.info

### ISSUE THREAD

**Issue by lightning20** [deepmind/pysc2#272]
Tried to install pysc2 on ubuntu18.4 with warcraft linux 4.7.1 and map package Ladder 2019 Season 1. When run a sample code zerg_agent.py, it give error as below. I am a newbie. Is it possible give any suggestion, thanks.

python zerg_agent.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
I0524 10:06:19.386617 140062606419776 sc_process.py:110] Launching SC2: /home/d/StarCraftII/Versions/Base70154/SC2_x64 -listen 127.0.0.1 -port 24676 -dataDir /home/d/StarCraftII/ -tempDir /tmp/sc-9q1vetas/ -displayMode 0 -windowwidth 640 -windowheight 480 -windowx 50 -windowy 50
I0524 10:06:19.390377 140062606419776 remote_controller.py:163] Connecting to: ws://127.0.0.1:24676/sc2api, attempt: 0, running: True
Version: B70326 (SC2.2018Season4)
Build: Nov 27 2018 03:26:30
Command Line: '"/home/d/StarCraftII/Versions/Base70154/SC2_x64" -listen 127.0.0.1 -port 24676 -dataDir /home/d/StarCraftII/ -tempDir /tmp/sc-9q1vetas/ -displayMode 0 -windowwidth 640 -windowheight 480 -windowx 50 -windowy 50'
Starting up...
Startup Phase 1 complete
Fatal Error:
Failed to find .build.info file at path: /home/d/StarCraftII/.build.info
Terminating...
W0524 10:06:20.393357 140062606419776 remote_controller.py:160] SC2 isn't running, so bailing early on the websocket connection.
I0524 10:06:20.393687 140062606419776 sc_process.py:201] Shutdown gracefully.
I0524 10:06:20.393838 140062606419776 sc_process.py:182] Shutdown with return code: -15
Traceback (most recent call last):
  File "zerg_agent.py", line 45, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "zerg_agent.py", line 27, in main
    visualize=True) as env:
  File "/usr/local/lib/python3.6/dist-packages/pysc2/env/sc2_env.py", line 276, in __init__
    self._launch_sp(map_inst, interfaces[0])
  File "/usr/local/lib/python3.6/dist-packages/pysc2/env/sc2_env.py", line 351, in _launch_sp
    want_rgb=interface.HasField("render"))]
  File "/usr/local/lib/python3.6/dist-packages/pysc2/run_configs/platforms.py", line 208, in start
    want_rgb=want_rgb, extra_args=extra_args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pysc2/run_configs/platforms.py", line 97, in start
    self, exec_path=exec_path, version=version, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pysc2/lib/sc_process.py", line 116, in __init__
    self._host, self._port, self, timeout_seconds=timeout_seconds)
  File "/usr/local/lib/python3.6/dist-packages/pysc2/lib/remote_controller.py", line 143, in __init__
    sock = self._connect(host, port, proc, timeout_seconds)
  File "/usr/local/lib/python3.6/dist-packages/pysc2/lib/stopwatch.py", line 201, in _stopwatch
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pysc2/lib/remote_controller.py", line 174, in _connect
    raise ConnectError("Failed to connect to the SC2 websocket. Is it up?")
pysc2.lib.remote_controller.ConnectError: Failed to connect to the SC2 websocket. Is it up?
I0524 10:06:20.450495 140062606419776 sc2_env.py:656] Environment Close

**Comment by ethan052** [comment]
Did you download SC2 4.7.1 from
https://github.com/Blizzard/s2client-proto#downloads ?

.build.info is the last unzipped file, may be the file that you get was broken.

HTTP request sent, awaiting response... 200 OK
Length: 3321311758 (3.1G) [application/zip]
Saving to: ‘SC2.4.7.1.zip’

**Comment by lightning20** [comment]
Really thankful ethan052.
The build.info was missing when unzip.

**Comment by lightning20** [comment]
Thanks again and close the issue

**Comment by mschen97** [comment]
THANKS
