### ISSUE TITLE
Can't start any agent

### ISSUE THREAD

**Issue by jjalexander** [deepmind/pysc2#284]
I am getting the following error:
TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given
whenever I try to run even the builtin AI agents.

Python: 3.8.0
Pip: 19.3.1
Pygame: 1.9.6
Pysc2: 3.0.0

StackTrace:

> PS C:\Users\Iulian> pysc2_agent --map CollectMineralShards
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Iulian\AppData\Local\Programs\Python\Python38-32\Scripts\pysc2_agent.exe\__main__.py", line 7, in <module>
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\pysc2\bin\agent.py", line 160, in entry_point
    app.run(main)
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\pysc2\bin\agent.py", line 150, in main
    run_thread(agent_classes, players, FLAGS.map, FLAGS.render)
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\pysc2\bin\agent.py", line 90, in run_thread
    with sc2_env.SC2Env(
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\pysc2\env\sc2_env.py", line 287, in __init__
    self._launch_game()
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\pysc2\env\sc2_env.py", line 355, in _launch_game
    self._sc2_procs = [
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\pysc2\env\sc2_env.py", line 356, in <listcomp>
    self._run_config.start(extra_ports=self._ports,
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\pysc2\run_configs\platforms.py", line 87, in start
    return sc_process.StarcraftProcess(
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\pysc2\lib\sc_process.py", line 135, in __init__
    logging.info("Launching SC2: %s", " ".join(args))
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\absl\logging\__init__.py", line 338, in info
    log(INFO, msg, *args, **kwargs)
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\absl\logging\__init__.py", line 485, in log
    _absl_logger.log(standard_level, msg, *args, **kwargs)
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\absl\logging\__init__.py", line 1047, in log
    super(ABSLLogger, self).log(level, msg, *args, **kwargs)
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\logging\__init__.py", line 1500, in log
    self._log(level, msg, args, **kwargs)
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\logging\__init__.py", line 1565, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given
Exception ignored in: <function Base.__del__ at 0x03099658>
Traceback (most recent call last):
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\pysc2\env\environment.py", line 160, in __del__
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\pysc2\env\sc2_env.py", line 752, in close
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\absl\logging\__init__.py", line 338, in info
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\absl\logging\__init__.py", line 485, in log
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\site-packages\absl\logging\__init__.py", line 1047, in log
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\logging\__init__.py", line 1500, in log
  File "c:\users\iulian\appdata\local\programs\python\python38-32\lib\logging\__init__.py", line 1565, in _log
TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given

**Comment by jjalexander** [comment]
NVM it's seems to be a problem in the logging library
