### ISSUE TITLE
traceback error when trying to view valid actions

### ISSUE THREAD

**Issue by flisz** [deepmind/pysc2#29]
I was trying to get some output similar to what is described in environments.md and have been having some issues.  I ran these in windows10 powershell, in case that helps. Do I need to add s2clientprotocol to path?

```
PS > python -m pysc2.bin.valid_actions
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\ProgramData\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\HODOR\desktop\flisz\pysc2\pysc2\bin\valid_actions.py", line 21, in <module>
    from pysc2.lib import actions
  File "pysc2\lib\__init__.py", line 23, in <module>
    from pysc2.lib.actions import Arguments
  File "pysc2\lib\actions.py", line 26, in <module>
    from s2clientprotocol import spatial_pb2 as sc_spatial
ImportError: No module named s2clientprotocol
```

**Comment by tewalds** [comment]
How did you install pysc2? If you did: "pip install pysc2" or "git clone .../pysc2.git; pip install pysc2/", it should have installed s2clientprotocol as a dependency. You could always fix it by doing: "pip install s2clientprotocol" or cloning https://github.com/Blizzard/s2client-proto and installing that, or otherwise getting it into your python path.

**Comment by tewalds** [comment]
I'm going to assume that worked and can close this issue.
