### ISSUE TITLE
"ValueError: Map 'Melee/Simple64.SC2Map' not found." on Debian 10

### ISSUE THREAD

**Issue by MislavJuric** [deepmind/pysc2#301]
Hello guys,

I have an error when I try to play the game as a human. I can run the agent on the map `Simple64` like so:

`$ python -m pysc2.bin.agent --map Simple64`

But running:

`$ python -m pysc2.bin.play --map Simple64`

produces the following output:

```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/site-packages/pysc2/bin/play.py", line 234, in <module>
    app.run(main)
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/site-packages/pysc2/bin/play.py", line 155, in main
    create.local_map.map_data = map_inst.data(run_config)
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/site-packages/pysc2/maps/lib.py", line 87, in data
    return run_config.map_data(self.path, self.players)
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/site-packages/pysc2/run_configs/lib.py", line 126, in map_data
    raise ValueError("Map '%s' not found." % map_name)
ValueError: Map 'Melee/Simple64.SC2Map' not found.
```

**What do you think the issue could be?** I downloaded all of the maps and placed them in `~/StarcraftII/Maps` folder.

Thank you in advance!

**Comment by KingKeet** [comment]
Check the file size of your map. I've seen the code break if it happens to download an empty map file. If that's the case, maybe try to redownload/reinstall the map

**Comment by MislavJuric** [comment]
Solved it. Downloaded the Meele map pack from this [link](https://github.com/Blizzard/s2client-proto#downloads).

**Comment by KingKeet** [comment]
> Check the file size of your map. I've seen the code break if it happens to download an empty map file. If that's the case, maybe try to redownload/reinstall the map

So was this the problem?

**Comment by MislavJuric** [comment]
@KingKeet no, I didn't download the Meele map pack from the link I supplied. I overlooked that folder set when downloading the folders. Strange that the agent ran successfully without the map.
