### ISSUE TITLE
IndexError: index 255 is out of bounds for axis 0 with size 2 when trying to play the game as human

### ISSUE THREAD

**Issue by MislavJuric** [deepmind/pysc2#304]
Hello guys,

I am having the following error when I try to play the game as human:

`IndexError: index 255 is out of bounds for axis 0 with size 2`

Here is the complete output log:

```
(aisc) mislav@mislavovo-racunalo:~$ python -m pysc2.bin.play --map Simple64 --rgb_screen_size 0
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
I0626 18:58:42.736707 139978139449152 sc_process.py:135] Launching SC2: /home/mislav/StarCraftII/Versions/Base56787/SC2_x64 -listen 127.0.0.1 -port 20586 -dataDir /home/mislav/StarCraftII/ -tempDir /tmp/sc-ryogjfx6/
I0626 18:58:42.739721 139978139449152 remote_controller.py:167] Connecting to: ws://127.0.0.1:20586/sc2api, attempt: 0, running: True
Version: B56787 (SC2.3.17)
Build: Aug 25 2017 15:00:49
Command Line: '"/home/mislav/StarCraftII/Versions/Base56787/SC2_x64" -listen 127.0.0.1 -port 20586 -dataDir /home/mislav/StarCraftII/ -tempDir /tmp/sc-ryogjfx6/'
Starting up...
Startup Phase 1 complete
I0626 18:58:43.743144 139978139449152 remote_controller.py:167] Connecting to: ws://127.0.0.1:20586/sc2api, attempt: 1, running: True
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:20586 (20586)
Startup Phase 3 complete. Ready for commands.
I0626 18:58:44.745230 139978139449152 remote_controller.py:167] Connecting to: ws://127.0.0.1:20586/sc2api, attempt: 2, running: True
Requesting to join a single player game
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface enabled
Configure: score interface enabled
Configure: render interface disabled
Entering load game phase.
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Game has started.
Sending ResponseJoinGame
Exception in thread Renderer:
Traceback (most recent call last):
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/site-packages/pysc2/lib/renderer_human.py", line 1706, in render_thread
    self.render_obs(obs)
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/site-packages/pysc2/lib/renderer_human.py", line 69, in _with_lock
    return func(*args, **kwargs)
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/site-packages/pysc2/lib/renderer_human.py", line 1724, in render_obs
    surf.draw(surf)
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/site-packages/pysc2/lib/renderer_human.py", line 658, in <lambda>
    lambda surf: self.draw_raw_layer(surf, from_obs, name, color))
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/home/mislav/anaconda3/envs/aisc/lib/python3.7/site-packages/pysc2/lib/renderer_human.py", line 1668, in draw_raw_layer
    surf.blit_np_array(color[layer])
IndexError: index 255 is out of bounds for axis 0 with size 2

Wrote replay to: /home/mislav/StarCraftII/Replays/local/Simple64_2020-06-26-16-59-09.SC2Replay
took 20.079 seconds for 447 steps: 22.262 fps
RequestQuit command received.
Closing Application...
unable to parse websocket frame.
I0626 18:59:09.193591 139978139449152 sc_process.py:232] Shutdown gracefully.
I0626 18:59:09.193736 139978139449152 sc_process.py:210] Shutdown with return code: -15
```

I have a conda virtual environment in which I am running this. **I get a completely black screen which says Startcraft Viewer.** Again, it is completely black, with nothing rendered in it. I can use the keyboard shortcuts to exit the Starcraft Viewer (F4).

**What do you think the problem is here?** 

Thank you in advance!

**Comment by MislavJuric** [comment]
This isssue is due to the fact that I was using [Linux package version](https://github.com/Blizzard/s2client-proto#downloads) 3.17 instead of the newest package version, which is 4.10.

**Comment by zyp57783** [comment]
I have the same problem when I render replay file generated by 4.7.1 SC2 client, should I update my client to 4.10 to watch the replay?
