### ISSUE TITLE
How to read old 3.16.1 replays for ML purposes ?

### ISSUE THREAD

**Issue by GDelevoye** [deepmind/pysc2#323]
Hello everyone, 

I am new to pySC2. I want to do ML research on the replay datasets from version 3.16.1 found here: https://github.com/Blizzard/s2client-proto#downloads

So, I downloaded and installed the 3.16.1 since I want to do ML with these data. I am running Ubuntu 20 LTS with a nvidia dedicated card (all drivers installed).  Everything was going quite fine. However when I run pysc2.bin.agent I get a very annoying output like this one (click):

<details>

```console
user@A320MA://data/StarCraftII/Versions$ python -m pysc2.bin.agent --map Simple64
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
I0107 17:45:50.539229 140086354175808 sc_process.py:135] Launching SC2: /data/StarCraftII/Versions/Base55958/SC2_x64 -listen 127.0.0.1 -port 24948 -dataDir /data/StarCraftII/ -tempDir /tmp/sc-f1sbz4is/
I0107 17:45:50.543418 140086354175808 remote_controller.py:166] Connecting to: ws://127.0.0.1:24948/sc2api, attempt: 0, running: True
Version: B55958 (SC2.3.16)
Build: Jul 31 2017 13:19:41
Command Line: '"/data/StarCraftII/Versions/Base55958/SC2_x64" -listen 127.0.0.1 -port 24948 -dataDir /data/StarCraftII/ -tempDir /tmp/sc-f1sbz4is/'
Starting up...
Startup Phase 1 complete
I0107 17:45:51.548355 140086354175808 remote_controller.py:166] Connecting to: ws://127.0.0.1:24948/sc2api, attempt: 1, running: True
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:24948 (24948)
Startup Phase 3 complete. Ready for commands.
I0107 17:45:52.550020 140086354175808 remote_controller.py:166] Connecting to: ws://127.0.0.1:24948/sc2api, attempt: 2, running: True
Requesting to join a single player game
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface enabled
Configure: score interface enabled
Configure: render interface disabled
Entering load game phase.
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Game has started.
Sending ResponseJoinGame
I0107 17:45:56.997645 140086354175808 sc2_env.py:314] Environment is ready
I0107 17:45:56.998006 140086354175808 sc2_env.py:506] Starting episode 1: [random, random] on Simple64
Exception in thread Renderer:
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/anaconda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/renderer_human.py", line 1706, in render_thread
    self.render_obs(obs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/renderer_human.py", line 69, in _with_lock
    return func(*args, **kwargs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/renderer_human.py", line 1724, in render_obs
    surf.draw(surf)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/renderer_human.py", line 658, in <lambda>
    lambda surf: self.draw_raw_layer(surf, from_obs, name, color))
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/renderer_human.py", line 1668, in draw_raw_layer
    surf.blit_np_array(color[layer])
IndexError: index 255 is out of bounds for axis 0 with size 2
   0/no_op                                              ()
   1/move_camera                                        (1/minimap [64, 64])
   2/select_point                                       (6/select_point_act [4]; 0/screen [84, 84])
   3/select_rect                                        (7/select_add [2]; 0/screen [84, 84]; 2/screen2 [84, 84])
   4/select_control_group                               (4/control_group_act [5]; 5/control_group_id [10])
   5/select_unit                                        (8/select_unit_act [4]; 9/select_unit_id [500])
 264/Harvest_Gather_screen                              (3/queued [2]; 0/screen [84, 84])
  12/Attack_screen                                      (3/queued [2]; 0/screen [84, 84])
  13/Attack_minimap                                     (3/queued [2]; 1/minimap [64, 64])
 269/Harvest_Return_quick                               (3/queued [2])
 274/HoldPosition_quick                                 (3/queued [2])
 549/Effect_Spray_minimap                               (3/queued [2]; 1/minimap [64, 64])
  40/Build_Assimilator_screen                           (3/queued [2]; 0/screen [84, 84])
  55/Build_Forge_screen                                 (3/queued [2]; 0/screen [84, 84])
  57/Build_Gateway_screen                               (3/queued [2]; 0/screen [84, 84])
 451/Smart_screen                                       (3/queued [2]; 0/screen [84, 84])
 452/Smart_minimap                                      (3/queued [2]; 1/minimap [64, 64])
 453/Stop_quick                                         (3/queued [2])
  70/Build_Pylon_screen                                 (3/queued [2]; 0/screen [84, 84])
 331/Move_screen                                        (3/queued [2]; 0/screen [84, 84])
 332/Move_minimap                                       (3/queued [2]; 1/minimap [64, 64])
 333/Patrol_screen                                      (3/queued [2]; 0/screen [84, 84])
 334/Patrol_minimap                                     (3/queued [2]; 1/minimap [64, 64])
 230/Effect_Spray_screen                                (3/queued [2]; 0/screen [84, 84])
Unable to process action with ability_id: 3795
Took 0.968 seconds for 93 steps: 96.042 fps
I0107 17:45:57.966322 140086354175808 sc2_env.py:752] Environment Close
RequestQuit command received.
Closing Application...
unable to parse websocket frame.
I0107 17:45:58.072691 140086354175808 sc_process.py:232] Shutdown gracefully.
I0107 17:45:58.072925 140086354175808 sc_process.py:210] Shutdown with return code: -15
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/bin/agent.py", line 164, in <module>
    app.run(main)
  File "/opt/anaconda/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/opt/anaconda/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/bin/agent.py", line 150, in main
    run_thread(agent_classes, players, FLAGS.map, FLAGS.render)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/bin/agent.py", line 108, in run_thread
    run_loop.run_loop(agents, env, FLAGS.max_agent_steps, FLAGS.max_episodes)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/env/run_loop.py", line 48, in run_loop
    timesteps = env.step(actions)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/env/available_actions_printer.py", line 32, in step
    all_obs = super(AvailableActionsPrinter, self).step(*args, **kwargs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/env/base_env_wrapper.py", line 42, in step
    return self._env.step(*args, **kwargs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/env/sc2_env.py", line 548, in step
    return self._step(step_mul)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/env/sc2_env.py", line 565, in _step
    return self._observe(target_game_loop=target_game_loop)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/env/sc2_env.py", line 670, in _observe
    self._get_observations(target_game_loop)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/env/sc2_env.py", line 636, in _get_observations
    self._obs, self._agent_obs = zip(*self._parallel.run(
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/run_parallel.py", line 56, in run
    return [funcs[0]()]
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/env/sc2_env.py", line 632, in parallel_observe
    agent_obs = f.transform_obs(obs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/features.py", line 1178, in transform_obs
    [self.reverse_action(a).function for a in obs.actions],
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/features.py", line 1178, in <listcomp>
    [self.reverse_action(a).function for a in obs.actions],
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/features.py", line 1773, in reverse_action
    return func_call_ability(cmd.ability_id, actions.cmd_quick, queue)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/features.py", line 1714, in func_call_ability
    raise ValueError("Unknown ability_id: %s, type: %s. Likely a bug." % (
ValueError: Unknown ability_id: 3674, type: cmd_quick. Likely a bug.
I0107 17:45:58.159951 140086354175808 sc2_env.py:752] Environment Close
I0107 17:45:58.160168 140086354175808 sc2_env.py:752] Environment Close
```
</details>

if I use --rgb_screen_size 0 however, I get a black PyGame window with the following traceback:

<details>

```console
user@A320MA://data/StarCraftII/Versions$ python -m pysc2.bin.play --map Simple64 --rgb_screen_size 0
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
I0107 17:54:51.112322 140068808038208 sc_process.py:135] Launching SC2: /data/StarCraftII/Versions/Base55958/SC2_x64 -listen 127.0.0.1 -port 15958 -dataDir /data/StarCraftII/ -tempDir /tmp/sc-y3f0im_y/
I0107 17:54:51.117292 140068808038208 remote_controller.py:166] Connecting to: ws://127.0.0.1:15958/sc2api, attempt: 0, running: True
Version: B55958 (SC2.3.16)
Build: Jul 31 2017 13:19:41
Command Line: '"/data/StarCraftII/Versions/Base55958/SC2_x64" -listen 127.0.0.1 -port 15958 -dataDir /data/StarCraftII/ -tempDir /tmp/sc-y3f0im_y/'
Starting up...
Startup Phase 1 complete
I0107 17:54:52.122473 140068808038208 remote_controller.py:166] Connecting to: ws://127.0.0.1:15958/sc2api, attempt: 1, running: True
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:15958 (15958)
Startup Phase 3 complete. Ready for commands.
I0107 17:54:53.124129 140068808038208 remote_controller.py:166] Connecting to: ws://127.0.0.1:15958/sc2api, attempt: 2, running: True
Requesting to join a single player game
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface enabled
Configure: score interface enabled
Configure: render interface disabled
Entering load game phase.
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Game has started.
Sending ResponseJoinGame
Exception in thread Renderer:
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/anaconda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/renderer_human.py", line 1706, in render_thread
    self.render_obs(obs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/renderer_human.py", line 69, in _with_lock
    return func(*args, **kwargs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/renderer_human.py", line 1724, in render_obs
    surf.draw(surf)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/renderer_human.py", line 658, in <lambda>
    lambda surf: self.draw_raw_layer(surf, from_obs, name, color))
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/renderer_human.py", line 1668, in draw_raw_layer
    surf.blit_np_array(color[layer])
IndexError: index 255 is out of bounds for axis 0 with size 2
```
</details> 

When I close the window, it seems like a game was indeed running although I didn't see anything

```console
Wrote replay to: /data/StarCraftII/Replays/local/Simple64_2021-01-07-16-55-15.SC2Replay
took 18.740 seconds for 406 steps: 21.665 fps
RequestQuit command received.
Closing Application...
I0107 17:55:15.987035 140068808038208 sc_process.py:232] Shutdown gracefully.
I0107 17:55:15.987290 140068808038208 sc_process.py:210] Shutdown with return code: -15
```

When I try to see a replay it first works then fails:

<details>

```console

guillaume@A320MA:~$ python -m pysc2.bin.play --replay /data/StarCraftII/Replays/local/Simple64_2021-01-07-17-31-46.SC2Replay
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
I0107 18:33:13.699497 140453121840960 sc_process.py:135] Launching SC2: /data/StarCraftII/Versions/Base55958/SC2_x64 -listen 127.0.0.1 -port 22097 -dataDir /data/StarCraftII/ -tempDir /tmp/sc-uvmdocx3/ -dataVersion 5BD7C31B44525DAB46E64C4602A81DC2 -eglpath libEGL.so.1
I0107 18:33:13.705436 140453121840960 remote_controller.py:166] Connecting to: ws://127.0.0.1:22097/sc2api, attempt: 0, running: True
Version: B55958 (SC2.3.16)
Build: Jul 31 2017 13:19:41
Command Line: '"/data/StarCraftII/Versions/Base55958/SC2_x64" -listen 127.0.0.1 -port 22097 -dataDir /data/StarCraftII/ -tempDir /tmp/sc-uvmdocx3/ -dataVersion 5BD7C31B44525DAB46E64C4602A81DC2 -eglpath libEGL.so.1'
Starting up...
Startup Phase 1 complete
I0107 18:33:14.709872 140453121840960 remote_controller.py:166] Connecting to: ws://127.0.0.1:22097/sc2api, attempt: 1, running: True
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:22097 (22097)
Startup Phase 3 complete. Ready for commands.
I0107 18:33:15.711472 140453121840960 remote_controller.py:166] Connecting to: ws://127.0.0.1:22097/sc2api, attempt: 2, running: True
Could not find map name for file: /tmp/sc-uvmdocx3/StarCraft II/TempReplayInfo.SC2Replay
----------------------- Replay info ------------------------
map_name: "Simple Test Map 64x64"
local_map_path: "Melee/Simple64.SC2Map"
player_info {
  player_info {
    player_id: 1
    race_requested: Random
    race_actual: Zerg
  }
  player_result {
    player_id: 1
    result: Tie
  }
  player_apm: 0
}
player_info {
  player_info {
    player_id: 2
    race_requested: Random
    race_actual: Protoss
  }
  player_result {
    player_id: 2
    result: Tie
  }
  player_apm: 11
}
game_duration_loops: 243
game_duration_seconds: 10.848971366882324
game_version: "3.16.1.55958"
data_build: 55958
base_build: 55958
data_version: "5BD7C31B44525DAB46E64C4602A81DC2"

------------------------------------------------------------
Configuring interface options
RequestQuit command received.
Closing Application...
I0107 18:33:15.817319 140453121840960 sc_process.py:232] Shutdown gracefully.
I0107 18:33:15.817530 140453121840960 sc_process.py:210] Shutdown with return code: -15
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/bin/play.py", line 234, in <module>
    app.run(main)
  File "/opt/anaconda/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/opt/anaconda/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/bin/play.py", line 192, in main
    controller.start_replay(start_replay)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/remote_controller.py", line 99, in _valid_status
    return func(self, *args, **kwargs)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/remote_controller.py", line 74, in _check_error
    return check_error(func(*args, **kwargs), error_enum)
  File "/opt/anaconda/lib/python3.8/site-packages/pysc2/lib/remote_controller.py", line 65, in check_error
    raise RequestError("%s.%s: '%s'" % (enum_name, error_name, details), res)
pysc2.lib.remote_controller.RequestError: SC2APIProtocol.ResponseStartReplay.Error.MissingOptions: ''

```

Would someone know what is wrong and how I could fix it ? :) Thx in advance

**Comment by MichalOp** [comment]
The 3.16 version seems unsupported by the newest pysc2, but you probably don't need to use it.

There is a somewhat hidden Blizzard script [https://github.com/Blizzard/s2client-proto/tree/master/samples/replay-api](https://github.com/Blizzard/s2client-proto/tree/master/samples/replay-api) that can be used to download a lot (>1 million probably) of replays for newer versions through Blizzard Developer API. I don't know why this script is not linked on the front page, they probably forgot about it.

**Comment by GDelevoye** [comment]
Thank you it really helped !
I creates a Blizzard account and downloaded with this script and it worked

Well... I just skipped all the downloads not corresponding to my version (not 3.16.1 anymore since I did a fresh reinstall) but like you said I don't really need them, I just needed lots of replays

Thank you !
