### ISSUE TITLE
Support for Version 5.0.X Replays?

### ISSUE THREAD

**Issue by windowshopr** [deepmind/pysc2#338]
Ran the random agent on the simple 64x64 map, saved a replay, then when I run:

`python -m pysc2.bin.play --replay RandomAgent/Simple64_2022-03-24-03-57-25.SC2Replay`

... I get:

```
Traceback (most recent call last):
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\pysc2\bin\play.py", line 234, in <module>
    app.run(main)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\pysc2\bin\play.py", line 174, in main
    run_config = run_configs.get(version=version)  # Replace the run config.
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\pysc2\run_configs\__init__.py", line 40, in get
    return max(configs.values(), key=lambda c: c.priority())(version=version)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\pysc2\run_configs\platforms.py", line 123, in __init__
    version=version, cwd="Support64")
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\pysc2\run_configs\platforms.py", line 63, in __init__
    data_dir=base_dir, tmp_dir=None, version=version, cwd=cwd, env=env)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\pysc2\run_configs\lib.py", line 112, in __init__
    self.version = self._get_version(version)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\pysc2\run_configs\lib.py", line 220, in _get_version
    versions = self.get_versions(containing=game_version)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\pysc2\run_configs\platforms.py", line 111, in get_versions
    containing, sorted(ret.keys())))
ValueError: Unknown game version: 5.0.9. Known versions: ['3.16.1', '4.7.0', '4.7.1', 'latest'].
```

Any hope of getting the latest versions of the game supported? My current is 5.0.9. Really hope so as this would be huge for my project. Thanks!

**Comment by tewalds** [comment]
This doesn't exist on linux, and likely never will. You should be able to do it on Windows or Mac now if you use the latest version (or from git). The data versions are known, but you need to have the right version installed.
