### ISSUE TITLE
"InvalidMapData"

### ISSUE THREAD

**Issue by 98luobo** [deepmind/pysc2#340]
I popped out an error at runtime.

pysc2.lib.remote_controller.RequestError: SC2APIProtocol.ResponseCreateGame.Error.InvalidMapData: 'temporary map 'C:\Users\xx\AppData\Local\Temp\StarCraft II\TempLaunchMap.SC2Map' has invalid data.'

**Comment by 98luobo** [comment]
Traceback (most recent call last):
  File "main.py", line 73, in <module>
    run(config, logger)
  File "D:\Code Warehouse\paper_code_5_9\run.py", line 49, in run
    run_sequential(args=args, logger=logger)
  File "D:\Code Warehouse\paper_code_5_9\run.py", line 180, in run_sequential
    episode_batch = runner.run(test_mode=False)
  File "D:\Code Warehouse\paper_code_5_9\runners\episode_runner.py", line 116, in run
    reward, terminated, env_info = self.env.step(actions[0])
  File "d:\code warehouse\git warehouse\smac\smac\env\starcraft2\starcraft2.py", line 483, in step
    self.full_restart()
  File "d:\code warehouse\git warehouse\smac\smac\env\starcraft2\starcraft2.py", line 449, in full_restart
    self._launch()
  File "d:\code warehouse\git warehouse\smac\smac\env\starcraft2\starcraft2.py", line 343, in _launch
    self._controller.create_game(create)
  File "D:\Anaconda\envs\py36_marl\lib\site-packages\pysc2\lib\remote_controller.py", line 99, in _valid_status
    return func(self, *args, **kwargs)
  File "D:\Anaconda\envs\py36_marl\lib\site-packages\pysc2\lib\remote_controller.py", line 74, in _check_error
    return check_error(func(*args, **kwargs), error_enum)
  File "D:\Anaconda\envs\py36_marl\lib\site-packages\pysc2\lib\remote_controller.py", line 65, in check_error
    raise RequestError("%s.%s: '%s'" % (enum_name, error_name, details), res)
pysc2.lib.remote_controller.RequestError: SC2APIProtocol.ResponseCreateGame.Error.InvalidMapData: 'temporary map 'C:\Users\xx\AppData\Local\Temp\StarCraft II\TempLaunchMap.SC2Map' has invalid data.'

**Comment by Riccardos** [comment]
Hi, make sure you unzipped the map file with the correct password

**Comment by tewalds** [comment]
Either corrupt data, or it's a new map that doesn't work with an old version of the game.

**Comment by alghimo** [comment]
I had the same and was puzzled for a bit, but I realized that a previous run using a different map had somehow crashed and although the script I was running was stopped, the game window was still open with that other map, so once I closed it I could run my script again as usual.
