### ISSUE TITLE
Default random agent Out of Bound Error

### ISSUE THREAD

**Issue by doudoujay** [deepmind/pysc2#61]
When I ran Randomagent for BuildMarines, I got this error from time to time
```
Exception in thread Renderer:
Traceback (most recent call last):
  File "/home/jay/miniconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/jay/miniconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jay/miniconda2/lib/python2.7/site-packages/pysc2/lib/renderer_human.py", line 878, in render_thread
    self.render_obs(obs)
  File "/home/jay/miniconda2/lib/python2.7/site-packages/pysc2/lib/renderer_human.py", line 56, in _with_lock
    return func(*args, **kwargs)
  File "/home/jay/miniconda2/lib/python2.7/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/home/jay/miniconda2/lib/python2.7/site-packages/pysc2/lib/renderer_human.py", line 894, in render_obs
    surf.draw(surf)
  File "/home/jay/miniconda2/lib/python2.7/site-packages/pysc2/lib/renderer_human.py", line 352, in <lambda>
    lambda surf: self.draw_feature_layer(surf, feature))
  File "/home/jay/miniconda2/lib/python2.7/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/home/jay/miniconda2/lib/python2.7/site-packages/pysc2/lib/renderer_human.py", line 849, in draw_feature_layer
    surf.blit_np_array(feature.color(feature.unpack(self._obs.observation)))
  File "/home/jay/miniconda2/lib/python2.7/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/home/jay/miniconda2/lib/python2.7/site-packages/pysc2/lib/features.py", line 94, in color
    return self.palette[plane]
IndexError: index 16 is out of bounds for axis 0 with size 16
```

**Comment by gigayaya** [comment]
Same error here.
Please fix it.

**Comment by a3626a** [comment]
i think this issue is fixed already

**Comment by tewalds** [comment]
I think b594ad7 already fixed this. Please reopen if you can show that a different plane that needs to be clipped.
