### ISSUE TITLE
pysc2.lib.protocol.ConnectionError: Socket error (Windows 10)

### ISSUE THREAD

**Issue by freakman00** [deepmind/pysc2#66]
I got a socket error when executing the example below on windows 10. Same error with python 2 and 3 from Anaconda distribution. Sctarcarft version 3.17.0.56787. (Starcraft error code: 5A88BA99-05E4-48CC-9694-A6A7995135F4).

python -m pysc2.bin.agent --map CollectMineralShards --agent pysc2.agents.scripted_agent.CollectMineralShards

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\ProgramData\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build\bdist.win-amd64\egg\pysc2\bin\agent.py", line 112, in <module>
  File "build\bdist.win-amd64\egg\pysc2\lib\app.py", line 57, in run
  File "C:\ProgramData\Anaconda2\lib\site-packages\google\apputils\app.py", line 220, in really_start
    sys.exit(main(argv))
  File "build\bdist.win-amd64\egg\pysc2\bin\agent.py", line 98, in main
  File "build\bdist.win-amd64\egg\pysc2\bin\agent.py", line 74, in run_thread
  File "build\bdist.win-amd64\egg\pysc2\env\sc2_env.py", line 185, in __init__
  File "build\bdist.win-amd64\egg\pysc2\lib\remote_controller.py", line 151, in data
  File "build\bdist.win-amd64\egg\pysc2\lib\remote_controller.py", line 80, in _valid_status
  File "build\bdist.win-amd64\egg\pysc2\lib\stopwatch.py", line 197, in _stopwatch
  File "build\bdist.win-amd64\egg\pysc2\lib\remote_controller.py", line 147, in data_raw
  File "build\bdist.win-amd64\egg\pysc2\lib\protocol.py", line 127, in send
  File "build\bdist.win-amd64\egg\pysc2\lib\protocol.py", line 113, in send_req
  File "build\bdist.win-amd64\egg\pysc2\lib\stopwatch.py", line 197, in _stopwatch
  File "build\bdist.win-amd64\egg\pysc2\lib\protocol.py", line 86, in read
  File "build\bdist.win-amd64\egg\pysc2\lib\protocol.py", line 152, in _read
  File "C:\ProgramData\Anaconda2\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build\bdist.win-amd64\egg\pysc2\lib\protocol.py", line 66, in catch_websocket_connection_errors
pysc2.lib.protocol.ConnectionError: Socket error: [Errno 10054] Se ha forzado la interrupci=n de una conexi=n existente por el host remoto

**Comment by KevinCalderone** [comment]
Does it only fail on that minigame map? Likely the same issue as https://github.com/deepmind/pysc2/issues/53

**Comment by freakman00** [comment]
Exactly, only fails on that minigame. Thanks!
