### ISSUE TITLE
AttributeError on Mac

### ISSUE THREAD

**Issue by lcam** [deepmind/pysc2#71]
Hi,

Has anybody hit a similar error when running pysc2.bin.agent on a mac?  I installed pysc2 from git to make sure I have the most updated code, but I'm still hitting this error.  Any help would be appreciated, thanks!

python -m pysc2.bin.agent --map Simple64
NSWindowEdgeResizing is off!
Took 0.052 seconds for 0 steps: 0.000 fps
WARNING:root:Terminating attempt 0...
WARNING:root:Terminated.
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/pysc2/bin/agent.py", line 112, in <module>
    app.run(main)
  File "/Library/Python/2.7/site-packages/pysc2/lib/app.py", line 57, in run
    really_start(main or sys.modules["__main__"].main)
  File "/Library/Python/2.7/site-packages/google/apputils/app.py", line 220, in really_start
    sys.exit(main(argv))
  File "/Library/Python/2.7/site-packages/pysc2/bin/agent.py", line 98, in main
    run_thread(agent_cls, FLAGS.map, FLAGS.render)
  File "/Library/Python/2.7/site-packages/pysc2/bin/agent.py", line 77, in run_thread
    run_loop.run_loop([agent], env, FLAGS.max_agent_steps)
  File "/Library/Python/2.7/site-packages/pysc2/env/run_loop.py", line 35, in run_loop
    timesteps = env.reset()
  File "/Library/Python/2.7/site-packages/pysc2/env/base_env_wrapper.py", line 39, in reset
    return self._env.reset(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pysc2/env/sc2_env.py", line 218, in reset
    return self._step()
  File "/Library/Python/2.7/site-packages/pysc2/env/sc2_env.py", line 235, in _step
    agent_obs = self._features.transform_obs(self._obs.observation)
  File "/Library/Python/2.7/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pysc2/lib/features.py", line 262, in transform_obs
    out["screen"] = np.stack(
AttributeError: 'module' object has no attribute 'stack'

**Comment by tewalds** [comment]
You've got an old version of numpy. Upgrade to something past 1.10: https://docs.scipy.org/doc/numpy/reference/generated/numpy.stack.html .
