### ISSUE TITLE
Starcraft crash after loading complete.

### ISSUE THREAD

**Issue by SPINACHCEO** [deepmind/pysc2#75]
I tried open with command :
python -m pysc2.bin.play --map CollectMineralShards
or launch with -agent, the game crash after loading bar finish at loading screen.

Terminal showing the following exceptions:
`err = 3 Game/Contrib/macteam/libs/crashy/contrib/mach_override/mach_override.c:244
err = 3 Game/Contrib/macteam/libs/crashy/contrib/mach_override/mach_override.c:258
err = 3 Game/Contrib/macteam/libs/crashy/contrib/mach_override/mach_override.c:263
err = 3 /opt/blizzard/buildserver/data.noindex/repositories/sc2/branches/SC2.3.17/Game/Contrib/macteam/libs/ClampCursor/Contrib/mach_override/mach_override.c:244
err = 3 /opt/blizzard/buildserver/data.noindex/repositories/sc2/branches/SC2.3.17/Game/Contrib/macteam/libs/ClampCursor/Contrib/mach_override/mach_override.c:258
err = 3 /opt/blizzard/buildserver/data.noindex/repositories/sc2/branches/SC2.3.17/Game/Contrib/macteam/libs/ClampCursor/Contrib/mach_override/mach_override.c:263
NSWindowEdgeResizing is off!
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Common/ChunkCompression.cpp:50: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Exceptions.plist'
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Common/ChunkCompression.cpp:50: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Library/AppExceptions.bundle/Exceptions.plist'
took 3.679 seconds for 0 steps: 0.000 fps
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/pysc2/bin/play.py", line 183, in <module>
    app.run(main)
  File "/Library/Python/2.7/site-packages/pysc2/lib/app.py", line 57, in run
    really_start(main or sys.modules["__main__"].main)
  File "/Library/Python/2.7/site-packages/google/apputils/app.py", line 220, in really_start
    sys.exit(main(argv))
  File "/Library/Python/2.7/site-packages/pysc2/bin/play.py", line 150, in main
    save_replay=FLAGS.save_replay)
  File "/Library/Python/2.7/site-packages/pysc2/lib/renderer_human.py", line 917, in run
    self.init(controller.game_info(), controller.data())
  File "/Library/Python/2.7/site-packages/pysc2/lib/remote_controller.py", line 151, in data
    return static_data.StaticData(self.data_raw())
  File "/Library/Python/2.7/site-packages/pysc2/lib/remote_controller.py", line 80, in _valid_status
    return func(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pysc2/lib/remote_controller.py", line 147, in data_raw
    ability_id=True, unit_type_id=True))
  File "/Library/Python/2.7/site-packages/pysc2/lib/protocol.py", line 127, in send
    res = self.send_req(sc_pb.Request(**kwargs))
  File "/Library/Python/2.7/site-packages/pysc2/lib/protocol.py", line 113, in send_req
    return self.read()
  File "/Library/Python/2.7/site-packages/pysc2/lib/stopwatch.py", line 197, in _stopwatch
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pysc2/lib/protocol.py", line 86, in read
    response = self._read()
  File "/Library/Python/2.7/site-packages/pysc2/lib/protocol.py", line 152, in _read
    response_str = self._sock.recv()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Python/2.7/site-packages/pysc2/lib/protocol.py", line 63, in catch_websocket_connection_errors
    raise ConnectionError("Connection already closed. SC2 probably crashed. "
pysc2.lib.protocol.ConnectionError: Connection already closed. SC2 probably crashed. Check the error log.
Qis-iMac:A-Guide-to-DeepMinds-StarCraft-AI-Environment-master qihaoyan$ 2017-09-15 13:22:26.505 Blizzard Error[1520:382545] Blizzard Error Report ID: F7E12146-AA5C-419F-8F87-E027435EAA8A
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Common/ChunkCompression.cpp:50: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Exceptions.plist'
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Common/ChunkCompression.cpp:50: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '`

And then crash reporter launched with the following code:
F7E12146-AA5C-419F-8F87-E027435EAA8A

Does anyone know what is going on here ? I am running on macOS 10.13 and I even have the full version of Starcraft II.

**Comment by KevinCalderone** [comment]
This is the same issue as: deepmind/pysc2#53. The fix will be out soon in the 3.18 patch.

If you want to workaround it in the meantime, you can [revert your install back to the 3.16.1 build](https://github.com/deepmind/pysc2/issues/53#issuecomment-326829857).

**Comment by SPINACHCEO** [comment]
Thanks @tewalds ,
sorry for the late reply.
